variables:
  PROJECT_ID: "fifth-name-424318-q4"
  REGION: "us-west2"
  IMAGE_NAME: "static_web_site"

stages:
  - docker-build
  - test-acc
  - release
  
services:
  - docker:dind  
docker-build:
  # Use the official docker image.
  image: docker:20.10.7
  stage: docker-build
  services:
    -  name: docker:dind
       alias: docker
  
 
  script:
    - docker build --pull -t webapp .
    - docker save webapp > webapp.tar
  artifacts:
    untracked: false
    when: on_success
    access: all
    paths:
      - "webapp.tar"
    expire_in: 30 days
test-acc:
  image: docker:cli
  stage: test-acc
  services:
    - docker:dind
  script:
    - docker load < awebapp.tar
    - docker run -d -p 80:80  --name webapp webapp 
    - apk add --no-cache  --update curl
    - curl "http://docker:80" | grep -q "Dimension"

release image:
 stage: release
 image: docker:20.10.7
 services:
    - docker:dind
 script:
   - docker load < webapp.tar
   - docker tag webapp "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}" 
   - docker tag webapp "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
   - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
   - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}" 

